### PR TITLE
Make refreshTickets refresh all fields data

### PR DESCRIPTION
**Pull request by gnustavo**
Hi @ljay79 

I tried my hand at coding what I tried to describe in #92 

This is not a complete change. I would have to change documentation and discuss with you about offering this funcionality as new menu option, instead of co-opting the existing one, perhaps.

But I was able to test it and make it work here so I think you will be able to better understand what I had in mind.

I'd like to know what do you think about it.

### CODE REVIEW

**Comment by ljay79** [comment]
Thx. Will check it when im back from vacation in january

**Comment by ljay79** [comment]
Hi @gnustavo , i checked your changed and got a little confused.
If i see that correctly, you basically store the last fetched information from Jira in order to re-populate it into the spreadsheet.

Thats basically doing nothing then overwriting possible manual updates in the cells.
However it wont fetch any updates from JIRA itself.

Maybe i did not clearly got the point of your request / change.

**Comment by gnustavo** [comment]
Hi @ljay79 .

When one inserts a table containing the results of a filter for the first time I save in a Note at the head of the table the JSON representation of the filter parameters.

Then, when the user selects to refresh the filters in a sheet I look in all of the sheet cells for Notes containg a specific mark telling me that it's a Note containing the JSON representation of a filter. Then I act as if the user had asked me to reinsert the filter results in the same cell, which actually overrides the previous results with the new Jira state.

That's the general idea which I only wanted to make clearer to you. But it could/should be enhanced in a few ways before being integrated:

1. If the sheet has too many lines and columns it could take a long time to look for the cells containing Notes. We could require that the user selects a range containing the table head and look only there to avoid this.
2. If the table containing the refreshed data contains fewer lines than the previous refresh some lines of the previous refresh would remain in the spreadsheet. We could save in the Note the actual table dimensions to be able to clear it up before refreshing it.

I can work on these points but I want to know if you agree to the general idea first.

**Comment by ljay79** [comment]
Ok, then i understood you goal correctly. The code however (if i do not miss anything) would in best case only store and reuse the form submit values.
So yes, i see you found a way of storing the form data, but nothing yet to reuse it for fetching data from Jira and inserting it.

Generally speaking, the idea is now clear. I do have some possible solution in mind.
However i would not store anything of it inside a cells note or alike, rather then using the sheets or users property storage.

I was thinking more into the direction of allowing a user to store such form data (selected filter + choosen Jira fields) into a "Favorite Request" list. (Maybe different wording) but basically a list/storage of users favorite filter + the indiv. columns returned for that filter.

Now, the tricky part which i dont have a concept yet; how it improve convinience of choose a "Favorite Request" without having the user to navigate through multiple menus.
Here my first though was, keyboard shortcuts: *bummer*, not possible with Google Sheets.

Atm im thinking about a new "sidebar" navigation, including such "Favorite Request" menu. Once the sidebar is open, a user could always easily navigate to the menu with 2 or 3 clicks...

**Comment by gnustavo** [comment]
> So yes, i see you found a way of storing the form data, but nothing yet to reuse it for fetching data from Jira and inserting it.

But it already does! If you select refreshTickets from the menu it will refresh all the information about the issues in the sheet. At least, it worked for me. ;-)

Have you tried it?

> BTW: I guess you agree, if i do decline this merge request given above statements!?

Of course. This PR is a work in progress I made just to better show you what I had in mind. I'm not expecting you to accept it as is.

**Comment by ljay79** [comment]
..yes i see it now, it basically does/could work as you described.

**Comment by ljay79** [comment]
closed in favor for #181

**Pull request closed without merging**
