### PR TITLE
Fix for Authmode which was causing debug not to work when I ran on GAS

### PR DESCRIPTION
**Pull request by paul-lemon**
I have found an issue with AUTHMODE.
When I run the code on GAS it is running in AUTHMODE.LIMITED so the code block that enables debugging didn't work.
In my feature branch I have used this block of code to decide whether to show the menu for the new feature while the feature is still "BETA" so it was obvious it didnt work for me.

I did some debug logging in Code.gs to verify

    if (e && e.authMode != ScriptApp.AuthMode.NONE) {
        // Code below can run in AuthMode.LIMITED and AuthMode.FULL
        var userProps = PropertiesService.getUserProperties();
        debug.enable( (userProps.getProperty('debugging')=='true') );
        debug.info("Auth mode = "+e.authMode);
      }
This produced the log:-
    2019-01-16 08:33:35.572 CET Auth mode = LIMITED

### CODE REVIEW

**Comment by ljay79** [comment]
I know what you mean and i remember having a lot of trouble.
The debug object is accessing the users porperties storage, this wont work in unauthed mode (NONE).
On top of this, there was an flow issue, that the request is "onOpen" is called for new installations as well just before a user is able to authenticate the add-on etc.

I must say, im honestly not sure 100% anymore how exactly the circumstances have been, but i remember i spent quite some time coming to the current working solution :)

a) For your Beta switch; i would suggest to always develop on the code as it is the only version in your GAS. Without any state switches. The menu you mention, is available only for you anyway. I dont see a reason of having such switch implemented.

b) For this particular change in the _onOpen_ method, i would actually rather prefer keeping it as it was, à la "never change a running system" :) . If not, i would need to research, review and test this entire flow again :(

I know its kinda bad excuse; but honestly i remember doing it very carefully this way with specific porpose but can not remember in detail what the issue(s) have been doing it with the other AuthModes.

sry :/

**Comment by paul-lemon** [comment]
Hi,

I get your resistance to change that bit completely. The code change only allows the block to execute when AuthMode != NONE and I've executed the block many times so I'm confident its ok. However it would need full testing through the install process to be 100% so I'm fine if the change is not made.

However I do need debug output to work on GAS, so *something* needs to be done (just not this specific change :) ). I could look at another solution with environment configuration in the deployment i.e. when you deploy to a test environment logging always works and when you deploy to production it only works if the user has selected it. What do you think?

I will move the menu out of this block of code so it always shows. Feature switches could be something that you think about at some point so that big new features can be added into the production code base before it is all ready. Thats a thing that may be useful for this new feature. However that's another discussion. (see https://martinfowler.com/articles/feature-toggles.html if you havent already)

**Comment by ljay79** [comment]
Hi.
If your concern is about debugging and logs... this is all implemented
already.
You simply go to the "About" dialog in the add-on and switch on debugging.
Then it will show you a lot of info in your StackDriver account from Google
automatically.

Temporary dev debug i do either by adding a console.log line or a
debug.log() line which remove later on.
Beside the toggle of this specific menu item show/noshow, i dont see a
reason yet to make adjustments... but maybe im not fully getting your point.




Am Mi., 16. Jan. 2019 um 10:44 Uhr schrieb paul-lemon <
notifications@github.com>:

**Comment by paul-lemon** [comment]
Hi Jens

Thanks for the clarification - I had got the way you have set user preferences on the about page, its nice :)

When I test on GAS, the code is running in AuthMode.Limited. That means that the code to activate the debugging is not being executed.

    if (e && e.authMode != ScriptApp.AuthMode.NONE) {
        // Code below can run in AuthMode.LIMITED and AuthMode.FULL
        var userProps = PropertiesService.getUserProperties();
        debug.enable( (userProps.getProperty('debugging')=='true') ); <-- THIS LINE IS NOT EXECUTED
        debug.info("Auth mode = "+e.authMode);
      }

The general debug logging that is included is really useful when developing the features so it good to have it on.
I do sometimes add the occasional specific console.log but I try to avoid it when I can and use the debug mechanism you have developed.

**Comment by ljay79** [comment]
I will try to replicate your issue and see why.
I think i had that in the past and is due to the authorization flow of the
add-on which in your/our case is development only and doesnt go through the
install->auth process by default. I believe there was a way of authorizing
it semi-manually... but will need to check that first again... give me a
few days.

At the end; if this works better for you atm, no big deal; i just want to
have to tripple-checked before i might integrate this change into a main
branch of mine...
For your personal development environment, you obviously can change what
ever you like :)

Am Mi., 16. Jan. 2019 um 12:05 Uhr schrieb paul-lemon <
notifications@github.com>:

**Comment by ljay79** [comment]
Yep, that sounds like a better approach.

Maybe even simplier in the code like:

Adding a new constant: "FORCE_DEBUGON = false";

// - Original code
if (e && e.authMode == ScriptApp.AuthMode.FULL) {
    var userProps = PropertiesService.getUserProperties();
    debug.enable( (userProps.getProperty('debugging')=='true') );
}
// End of Original code
if(  FORCE_DEBUGON === true ) debug.enable(true);
...

"gulp deploy development" changes the value assignment of that constant
from "false" to "true" depending on environment.



Am Mi., 16. Jan. 2019 um 12:25 Uhr schrieb paul-lemon <
notifications@github.com>:

**Comment by paul-lemon** [comment]
Hi Jens,

I like the approach of moving the change out of the code block you want to stay unchanged.

I would prefer not to use the single constant approach and have a controller reading a JSON file if thats ok with you. Its just as much work and means that new properties (and feature switches....) can easily be added.
It's your code base though and I can work however you like.

I think the requirements should be:-
1. Debug logging is off by default when running locally.
2. Deployment by default uses the production config (no debug logging code unless turned on by the user) - just to avoid accidents.
3. Deployment when the development environment is specified in the gulp command should use have debug logging turned on
Let me know your thoughts.

**Comment by ljay79** [comment]
Sound good, go ahead with your approach.
Try to keep complexity low and resulting production code clean and less
confusing.

Am Mi., 16. Jan. 2019 um 13:19 Uhr schrieb paul-lemon <
notifications@github.com>:

**Comment by paul-lemon** [comment]
@ljay79  I've made quite a large commit for this PR.
Most of the code comes from adding unit tests around Code.gs and onOpen - Since this file is so critical and you want to avoid change I felt better leaving some unit tests around it to protect it and validate it. The mocks for the GAS libraries will make testing easier and expand upon as the codebase grows
I also removed the gulp-diff code as it had a number of issues and doesnt appear to be maintained

**Pull request merged**
