### PR TITLE
add feature Jira status report

### PR DESCRIPTION
**Pull request by meltzow**
hi,
with this PR it's possible to create a new report type named: "status report".

In jira there is a history of **all** changes of **all** fields of any jira issue. This can be requested by the jira REST API. This feature are only using the history of the "STATUS" field. With this, we create a XLS with the following colums 

**key** = <issueKey> with HTML Link
**issuetype** = <Typ of issue> for example story, bug, etc...
**created** = <timestamp of the status change entry>
**field** = "status" (currently a constant - but prepared for a later possible extension to support ALL fields
**fromString** = <Stringvalue of status before changing> 
**toString** = < Stringvalue of status after changing>

For example with this feature its possible to analyse the status history to create a cycletime report for all issues (of filtered by a filter)

Later its possible to extend this PR to support ALL fields. but this wasn't our scope.
Thank you to all commiters. 

have fun with this.

### CODE REVIEW

**Comment by ljay79** [comment]
Thx for this PR, give me a little time for reviewing and testing.
Do I need to prepare anything on a jira cloud to test this?

**Comment by meltzow** [comment]
hi,
you just need the auth for jira and some filters like in the other usecases. 
We successfully test it with jira cloud.

**Comment by ljay79** [comment]
@meltzow just tried it in development mode in google sheet, and its not working.
It already fails very early because of wrong implementation of class usage. From what i see, you seem to never have it deployed to GAS actually?

`ReferenceError: "changelogTableRendererDefault_" ist nicht definiert. at ChangelogRendererFactory_(models/renderer/ChangelogRendererFactory:16) at [unknown function](models/jira/ChangelogTable:276) at [unknown function](controllers/changelogReport:110) at [unknown function](models/jira/IssueSearch:140) at [unknown function](controllers/changelogReport:135) at callbackGetAllChangelogs(controllers/changelogReport:31)`

In the GAS environment (which is not node) it does not have any module require definitions and therefor is doesnt know where to look for your used class `changelogTableRendererDefault_` because its defined in a file not included/loaded at runtime.

**Comment by ljay79** [comment]
`var changelogTableRendererDefault_ = require('../renderer/ChangelogTableRendererDefault.gs').ChangelogTableRendererDefault_;`
in GAS, this line in the header would be commented out and not interpreted.

**Comment by meltzow** [comment]
hi,
that really strange. we have running it in our GAS and its working fine here.

**Comment by ljay79** [comment]
Are you using the procedures outlined here in the Readme?

**Comment by meltzow** [comment]
yes, I deploy it with "gulp deploy" (for example)

**Comment by meltzow** [comment]
but I understand what your log describe. The source in ChangelogRendererFactory.gs 

`return changelogTableRendererDefault_(ChangelogeTable);`

must not work. There is no "changelogTableRendererDefault_" method in GAS scope.  the node require statement ist comment out here. thats really strange

**Comment by meltzow** [comment]
is it possible for you to fix it? It's a little bit stressful at my site.

**Comment by ljay79** [comment]
Would require some refactoring from my site. Maybe u use some newer GAS features I am nit aware of, because usually it should fail right away for same reason in your env too.

**Comment by paul-lemon** [comment]
Hi

Noticed this conversation going on. I think the problem is case consistency in the variables.

`var changelogTableRendererDefault_ = require('../renderer/ChangelogTableRendererDefault.gs').ChangelogTableRendererDefault_`

In the node environment the class from `'../renderer/ChangelogTableRendererDefault.gs'` will be in the variable `changelogTableRendererDefault_` with a lower case C. 

In GAS the class is called `ChangelogTableRendererDefault_` with a capital C. 

I recommend replacing all instances of `changelogTableRendererDefault_` in the file to `ChangelogTableRendererDefault_` and then try it on GAS - I think it will work

Paul

**Comment by meltzow** [comment]
sorry for my late response. Here is the screenshot 
screenshot

I hope it helps. 
May I help any more?

**Comment by ljay79** [comment]
Yeah thanks, Its actually already obsolete. I have been able to correct the problematic parts and started refactoring it overall :)
Im currently migrating into into the future best practice "sidebar" panel now and will add field selection as well as custom layouts.

Btw: Can you think of a usefull different layout / way of visualizing it in the sheet? In a way it makes sense to end users.

**Comment by meltzow** [comment]
ok, we discussed the sheet layout a lot. Sure it's not nice but it's the only one where our needs are covered. We used this sheet as rawdata for more analysis in other sheets. 
The column "field" is optional in the current layout. Perhaps after your refactoring and with field selection support its no more useless. 
Perhaps it will be great if the 2 row contains some manually sheet-filters at the column-headers.

**Comment by ljay79** [comment]
The branch "https://github.com/ljay79/jira-tools/tree/feature/status-report" has now my latest changes at works with initial testing.
If you get a chance, feel free to download that branch and test on your GAS sheet.

I will now prepare a few test scripts and then prepare a release asap.
If you have any idea/suggestion for a second "table layout" for such report, please let me know.

**Comment by ljay79** [comment]
@meltzow i hav released version 1.4.10 last weekend. Happy to receive your feedback for the "Changelog report".

**Pull request merged**
