### PR TITLE
Refactor storage access

### PR DESCRIPTION
**Pull request by ljay79**
Didnt like the way to access storage through a getter method everytime, changed to object style.

### CODE REVIEW

**Comment by ljay79** [comment]
@paul-lemon sry, i tried but im bad at Javascript and blody newbie on node unit testing.
I wasnt able on a short hand to resolve the changes in _Storage_ implications to the unit tests - they do fail atm. Could you take care of this pls?

**Comment by paul-lemon** [comment]
Hi,

This looks really nice and much more readable. I've a couple of comments on the code but I have to say it's great that you are cleaning some of this stuff up.

For the unit tests how do you want to go about it? Shall I start a unit test in test/Storage.test.js and do a couple of tests so you can get the hang of it or would you like me to do it all. I don't mind either option for this pull request - whatever you feel comfortable with and helps you move forward.

Paul

**Comment by ljay79** [comment]
Yeah i would say, just do the Storage unit test all yourself, i will try to learn by reading it :)

I'm still trying to understand the inclusions and mocks and how it all works together..
Given my limited time, im actually trying (since 3+ weeks) to focus on a new feature regarding #92 and similar.

The new development stuff contributed by you with gulp and clasp makes my life already much easier - very much appriciated.
The TDD approach is awesome too, just this particual part adds a big hurdle right now to me...

**Comment by paul-lemon** [comment]
Its worth approaching asap - the TDD will make you faster because you can use the tests to run the code locally before you can test it in the UI on GAS
https://medium.freecodecamp.org/a-quick-introduction-to-test-driven-development-with-jest-cac71cb94e50
https://medium.com/@rickhanlonii/understanding-jest-mocks-f0046c68e53c
Good luck! :)

**Comment by paul-lemon** [comment]
Fixed broken tests so its all back to green.
Will add tests for new code when you are ready with your decision about naming of "Storage" "Storage_" etc

**Comment by ljay79** [comment]
> Will add tests for new code when you are ready with your decision about naming of "Storage" "Storage_" etc

What you mean. My code commit is finished.
I know there now is _Storage_ and _Storage__ - the one being a actual storage class the other new one simply an access helper. Renaming suggestions?

**Comment by paul-lemon** [comment]
I put this comment on Storage.gs - 
_"I think the use of "Storage.doSomething" in the other files is more readable however this file is now a little bit confusing with two similar but different modules in it.

Storage_ (note the underscore) - this class actually looks after the mechanism of storing data which could be used for anything. Since this came from google originally (and you may want to update it if google do), I would leave it on its own in this file.
Storage (no underscore) - this class is specifically designed for storage of the applications settings. It has a dependency on Storage_
I recommend renaming "Storage" to "SettingsStorage" and moving it to its own file "SettingsStorage.gs"
This would make it clearer the purpose of the class and reduce possible confusion between the two.
I really can imagine accidentally editing the wrong class at some point!

That's your option though. Let me know"_

**Comment by ljay79** [comment]
Agree in general.
_SettingsStorage_ however is to specific, it is in fact the only way and only purpose of accessing the users storage in general. For settings, config, and later table meta storage... Settings is to specific.
How about simply: *AppStorage* ?

**Comment by ljay79** [comment]
> I put this comment on Storage.gs -
Cant find that anywhere?

**Comment by paul-lemon** [comment]
Its in the comments on the code in "Files Changed" 

Yes I see your point. I have to admit I am not sure why we are using two classes. Ultimately all of the user preferences are stored in PropertiesService.getUserProperties()
The only benefits from the google Storage_ class is it uses in memory caching which is trivial to implement in "Storage".
The google Storage_ class does have functionality to use another cache but it isnt being used.
I suggest deleting Storage_ and changing "Storage" let me hack that out in the comments part

**Comment by paul-lemon** [comment]
I've opened a pull request which deletes alot of lines of code and removed Storage_ completly

**Pull request merged**
