### PR TITLE
Update Storage.gs

### PR DESCRIPTION
**Pull request by paul-lemon**
Another refactor on storage

### CODE REVIEW

**Comment by ljay79** [comment]
This way you loose the functionality of having multiple Storages ie for UserProperties and antoher for ScriptProperties - which becomes probably handy soon.
You also did loose the prefixed storage handling, i would be unable to have 2 storage objects of same type for different prefixes.

I agree, such simplified class/object would make sense for current working code. But isnt flexible enough for future development.
IE: The original version is able and independent on what cache service is actually used; memory or other Google CacheService's (https://developers.google.com/apps-script/reference/cache/cache-service). 

The original one abstracts all this and incorporates Google services, the new one doesnt.
If ever, i think it might make more sense to de-link the Storage_ class from Googles github repo and extend it with our needed initialization method.

**Comment by ljay79** [comment]
Following (at least trying) the same approach - DRY.

With my IssueTable Metadata Storage in mind, i most likly will use a DocumentProperties Storage. So i believe, i will need more than just the 1 (hardcoded) user storage.

How about, tweaking the original "Storage_"? 
A week ago, i had only 1 function "getStorage()" just to initialize the "Storage_" instance purposly for user storage and prefix "jst".
My only intention was, to make this "getStorage()" more neat.. :)

Soon i will need something like:
a) _getStorage(a)_ <- settings and config
b) _getStorage(b)_ <- table meta storage
c) one day maybe more...

**Comment by paul-lemon** [comment]
Cool - lets close this one down then? :)

**Comment by ljay79** [comment]
yep, i think for now, we should close it. Sry

I think for now, i simply go for a better name of the new object.

**Pull request closed without merging**
